FROM rust:1.93.1-slim-bookworm

RUN apt-get update && apt-get install -y \
    pkg-config libssl-dev clang cmake build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY tests ./tests

RUN cargo build --release --bin rdrive-server && \
    cargo build --release --bin rdrive

ENV LOG_LEVEL=trace
ENV PORT=3000
ENV MAX_CONNECTION=128
ENV MAX_FILE_SIZE="12 * 1024 * 1024 * 1024"
ENV MASTER_KEY=77af778b51abd4a3c51c5ddd97204a9c3ae614ebccb75a606c3b6865aed6744e

CMD ["cargo", "test", "--release", "--test", "test_protocol"]
